apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: webserver
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/lab10-mynetwork: "true"
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/myDB
          image: localhost:32000/webserver:latest
          name: webserver
          ports:
            - containerPort: 8000
#              hostPort: 8000
              protocol: TCP
      restartPolicy: Always
